### ISSUE TITLE
Generic Parameter trait

### ISSUE THREAD

**Issue by jetuk** [pywr/pywr-next#135]
Some tasks to reduce some duplication in `pywr-core`.

- [x] Make `Parameter` trait generic over the calculated value type. #134
- [x] Use a single `ParameterIndex` that is also generic and tied to the calculated value type. #138 
- [x] Remove `as_any_mut` and corresponding dead code in `pywr-core/src/parameters/profiles/monthly.rs`. I think `as_any_mut` is only needed for this experiment that is now redundant. #139
